#!/bin/sh
DWM="$HOME/.dwm/"

imwheel &
dunst &

# Screen relusion
xrandr -s 1920x1080 &

# services
sudo systemctl start docker.service &

remapkey &

# keyboard rate: 150 delay + 40hz
xset r rate 150 40 &

# dwm bar
$DWM/dwmbar &

sleep 10s
feh --bg-fill $DWM/bg.jpg
