#!/usr/bin/sh
DWM="$HOME/.dwm/"

imwheel &
dunst &

# Screen relusion
xrandr -s 1920x1080 &

# services
sudo systemctl start docker.service &

# rebinds
setxkbmap -option caps:swapescape     # swap esc <> caps
setxkbmap -option altwin:swap_alt_win # swap alt <> meta
setxkbmap -option ctrl:menu_rctrl
xmodmap -e "keycode 105 = Menu"

# keyboard rate: 150 delay + 40hz
xset r rate 150 40 &

# dwm bar
$DWM/dwmbar &

google-chrome-stable &
sleep 10s
feh --bg-fill $DWM/bg.jpg
